% 06-2012
% Victor Barres
% USC Brain Project
% Script to create the dipoles dA function from the area dA functions
% generated by data_dA

function data_dipdA(varargin)

if isempty(varargin)
    subjName = getSubjName();
else
    subjName = varargin{1};
end

subjPath = sprintf('data\\%s',subjName);
load(sprintf('%s\\dipoles',subjPath));
load(sprintf('%s\\activ',subjPath));

dip2slab = dipoles.dip2slab;
numPoints = length(activ.time);
areaNames = {activ.area.name};
time = activ.time;

for d=1:length(dip2slab)
    list = dip2slab(d).names;
    waveform(d).brainArea = list;
    waveform(d).time = time;
    waveform(d).totalDur = activ.totalDur;
    waveform(d).dA = zeros(numPoints,1);
%     waveform(d).boxcar = zeros(numPoints,1);
    for l=1:length(list)
        f = strcmp(areaNames,list{l});
        if ~isempty(f==1)
%             waveform(d).boxcar = waveform(d).boxcar + activ.area(f).boxcar;
            waveform(d).dA = waveform(d).dA + activ.area(f).dA;
        end
    end
end
save(sprintf('%s\\waveform',subjPath),'waveform');
disp_wave2(subjName);
end